--- @meta hitokage.widgets.common

-------------------------------------------------------------------------------
--- Links to WidgetProps in 'hitokage-core\src\widgets\mod.rs'
---
--- @source hitokage-core\src\widgets\mod.rs
---
--- @class WidgetBoxProps
--- @field Box BoxProps
---
--- @class WidgetClockProps
--- @field Clock ClockProps
---
--- @class WidgetCpuProps
--- @field Cpu CpuProps
---
--- @class WidgetIconProps
--- @field Icon IconProps
---
--- @class WidgetLabelProps
--- @field Label LabelProps
---
--- @class WidgetMemoryProps
--- @field Memory MemoryProps
---
--- @class WidgetWeatherProps
--- @field Weather WeatherProps
---
--- @class WidgetWorkspaceProps
--- @field Workspace WorkspaceProps
