--- @meta hitokage.widgets.common

-------------------------------------------------------------------------------
--- Links to WidgetProps in 'hitokage-core\src\widgets\mod.rs'
---
--- @source hitokage-core\src\widgets\mod.rs
---
--- @class WidgetBoxProps
--- @field Box BoxProps
--- @class WidgetClockProps
--- @field Clock ClockProps
--- @class WidgetLabelProps
--- @field Label LabelProps
--- @class WidgetWorkspaceProps
--- @field Workspace WorkspaceProps
