copyright: Copyright &copy; 2024-Present Cody Duong
use_directory_urls: false
site_name: hitokage
site_description: Configurable status bar for windows
repo_url: https://github.com/codyduong/hitokage
repo_name: codyduong/hitokage
site_url: https://codyduong.github.io/hitokage
nav:
  - About:
      - index.md
      - Features: features.md
  - Download: download.md
  - Configuration:
      - configuration/index.md
      # - Recipes: configuration/recipes/
      # - Samples: configuration/samples/
  - API: api/

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.prune
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - footnotes
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
  - literate-nav:
      implicit_index: true
  - gen-files:
      scripts:
        - docs/gen_pages.py
  - tags
  - section-index

exclude_docs: |
  doc.md

extra_css:
  - stylesheets/extra.css
