[package]
name = "hitokage-macros"
version = "0.1.0"
edition = "2021"
authors = ["Cody Duong <cody.qd@gmail.com>"]

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.74"

[lib]
proc-macro = true
