name: docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'hitokage-lua-lib/**/*.lua'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Cache lua-language-server
        id: luals_cache
        uses: actions/cache@v3
        with:
          path: ~/.lua-language-server
          key: ${{ runner.os }}-lua-language-server

      - name: Install lua-language-server
        if: steps.luals_cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.lua-language-server
          wget https://github.com/LuaLS/lua-language-server/releases/download/3.11.1/lua-language-server-3.11.1-linux-x64.tar.gz
          tar -xzf lua-language-server-3.11.1-linux-x64.tar.gz -C ~/.lua-language-server

      - name: Cache Generated Docs
        id: docs_cache
        uses: actions/cache@v3
        with:
          path: ./docs/doc.md
          key: ${{ runner.os }}-lua-docs-${{ hashFiles('hitokage-lua-lib/**/*.lua') }}

      - name: Generate Lua Documentation
        if: steps.docs_cache.outputs.cache-hit != 'true'
        run: |
          ~/.lua-language-server/bin/lua-language-server --doc "hitokage-lua-lib" --doc_out_path "docs"

      - name: Build MkDocs Site
        run: |
          mkdocs build --clean

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1